### ISSUE TITLE
Is this part of PEPP-PT?

### ISSUE THREAD

**Issue by pdehaye** [ROBERT-proximity-tracing/documents#1]
Is this the same protocol as the one described yesterday by a colleague from @FraunhoferAISEC in a presentation organized by PEPP-PT?

**Comment by pdehaye** [comment]
clarified in the "Tribune" that it is

**Comment by patrickhanft** [comment]
In the `PEPP-PT-data-protection-information-security-architecture.pdf` document this project is also mentioned as 

> Description of the proposal for a joint French-German protocol: ROBERT (ROBust and privacypresERving proximity Tracing)

in the last reference at the end of that document.

**Comment by pdehaye** [comment]
Where is this document?

**Comment by patrickhanft** [comment]
Sorry, should have linked it: https://github.com/pepp-pt/pepp-pt-documentation

**Comment by pdehaye** [comment]
Thanks, hadn't seen they had *also* released all this
