### ISSUE TITLE
Bruno Sportisse Paper

### ISSUE THREAD

**Issue by pelinquin** [ROBERT-proximity-tracing/documents#34]
Au lieu de vous passer de la pommade sur:
-  l'INRIA: l'inventeur du numérique, excusez du peu !
- L'exception française...les autres ne sont pas aussi rigoureux que nous sur le droit numérique !
- L'exceptionnel travail de ses chercheurs alors que je n'ai pas trouvé de papier qui fasse une synthèse et prenne du recul par rapport aux deux approches Robert et DP-3T
- Un soit disante TaskForce hyper réactive alors qu'il n'y a ce jour pas un début de ligne de code en python sur Github
- l'ignorance de l'avancée du travail de DP-3T, qui propose ce jour des implémentations qui fonctionnent. J'ai un téléphone Android qui échange avec un iPhone sans pb.
- les qualité de l'OpenSource, ...allez, DIY, sortez vous les doigts du ... et contribuez, collaborez avec DP-3T puisque ce sont les plus en avance.

Le plus exceptionnel est d'insister sur le consentement et le caractère non obligatoire de cette app. Car si l'on constate dans quelques mois dans un pays que le contact tracing apporte un gain pour faire passer le Rt, alors nos chers politiques et directeurs de l'INRIA feront machine arrière et déclareront le port de l'application obligatoire, pour raison de santé publique.

La contribution de DP-3T n'est surement pas parfaite, mais elle a le mérite d'exister et de ne pas faire des déclarations publiques élogieuses, alors que pour Robert, c'est toute le contraire, on veut du CODE si vous voulez que les développeurs indépendant vous aident.

**Comment by vincent-grenoble** [comment]
Not very constructive, better close this thread.
By the way, the Inria logo changed two years ago and the "inventeur du monde numérique" mention has been removed... ;-)
