### ISSUE TITLE
KISSACT proposal

### ISSUE THREAD

**Issue by pelinquin** [ROBERT-proximity-tracing/documents#41]
I would be happy to help with such contribution:
https://github.com/pelinquin/kissact

**Comment by PRIVATICS-Inria** [comment]
Thank you for suggesting your help. However since “the KISSACT algorithm is based on the DP3T Low-Cost algorithm”, I think you’d better ask our Swiss colleagues behind DP-3T. Our adversary model is pretty much different, as well as our architecture.
