### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by MattiSG** [ROBERT-proximity-tracing/documents#5]
The current set of documents are made public but do not seem to be accompanied by any license, either as an independent document or as a mention in the binary files.
As such, they are thus apparently under copyright, and cannot be modified nor even redistributed.

In order to follow an “open source approach”, it would be important to add a license to this repository so that one can understand what are the expectations and legal rights for redistributing and building upon this content.

**Comment by btrd** [comment]
> Comme toutes les productions associées au projet STOPCOVID, elle sera mise en open source, sous licence MPL.

https://www.inria.fr/fr/contact-tracing-bruno-sportisse-pdg-dinria-donne-quelques-elements-pour-mieux-comprendre-les-enjeux

https://www.mozilla.org/en-US/MPL/2.0/

**Comment by PRIVATICS-Inria** [comment]
Good point, thank you @MattiSG for raising this topic. We added a CC BY-NC-SA licence for the documents.

**Comment by MattiSG** [comment]
Great, thanks! 🙂

**Comment by bzg** [comment]
Thanks for adding a license.

Mandatory nitpick: INRIA should rather use the [Open License 2.0](https://spdx.org/licenses/etalab-2.0.html) for these documents.

The Open License 2.0 does not prevent commercial reuse, but that's on purpose: as a public administration, INRIA falls under the [CRPA](https://www.legifrance.gouv.fr/affichSarde.do?reprise=true&page=1&idSarde=SARDOBJT000031372599) for such publications (and INRIA is an EPST, not an EPIC).

Also, on the practical side, I don't see what risks are avoided by limiting commercial reuse.

Your call, of course! And this can be fixed later on, when other priorities are less pressing.
