### ISSUE TITLE
Apple/Google API

### ISSUE THREAD

**Issue by pelinquin** [ROBERT-proximity-tracing/documents#53]
Could you share your tests of the EN(Exposure Notification) A/G API ?
I've got this but have problems to go further
![EB32673A-8350-42B2-944E-981ED874D054](https://user-images.githubusercontent.com/220488/80797289-c0de2180-8ba1-11ea-8f73-512d5845a4b8.png)

**Comment by vincent-grenoble** [comment]
Sorry, we're not relying on G/A API. Cannot help you.
