### ISSUE TITLE
Bleutooth version 5.2 ?

### ISSUE THREAD

**Issue by ArtefaktAI** [ROBERT-proximity-tracing/documents#56]
Hello,
I did not find information on which version of Bleutooth StopCovid application is based on.
It seems to me that you must have the Bleutooth version 5.2 to support Low Energy to provide the ability to track signal power and request the power level in connected devices.  Bleutooth v 5.2 standart is published in January 2020.
In this case, how many smartphones in France have this version of Bleutooth?
Thank you for the answer

**Comment by vincent-grenoble** [comment]
Thank you @ArtefaktAI. We agree. As you say, if we want the solution to be widely used, we cannot rely on any new Bluetooth feature that may not be widely available. Relying on the latest version is clearly not a good idea. We do not go into such details voluntarily, if ever we suggested the opposite, this is a mistake. Cheers.

**Comment by ArtefaktAI** [comment]
Thank you for your answer, but I did not fully understand it. So you confirm that the StopCovid application (and the  protocol Robert) is based on the Bleutooth version 5.2?

**Comment by vincent-grenoble** [comment]
Sorry if it's not clear. No, I hope (and think) there's no mechanism that would prevent it to be used with previous BLE versions.
